version: '3.8'

services:
  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SIGNING_KEY: ${JWT_SIGNING_KEY}
