spring:

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration/common

  application:
    name: trip-service

  datasource:
    url: jdbc:postgresql://${DB_URL}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public

  security:
    jwt_signing_key: ${JWT_SIGNING_KEY}

server:
  address: 0.0.0.0
  port: 8080