spring.application.name=trip_service

spring.datasource.url=jdbc:postgresql://${DB_URL}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.jwt_signing_key=${JWT_SIGNING_KEY}