spring:
  application:
    name: trip-service

  datasource:
    url: jdbc:postgresql://{DB_URL}/{DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

server:
  address: 0.0.0.0
  port: 8080